inform the user
git-svn-id: svn://munin-monitoring.org/munin/branches/debian@1667 47311dc8-50f3-0310-b975-824c5c5ab7df

diff --git a/lenny/trunk/debian/munin-node.postinst b/lenny/trunk/debian/munin-node.postinst
--- a/lenny/trunk/debian/munin-node.postinst
+++ b/lenny/trunk/debian/munin-node.postinst
@@ -26,11 +26,19 @@ init_plugins() {
 	if [ "$prevver" ]; then
 		echo -n "Initializing new plugins.."
 		munin-node-configure --shell --newer "${prevver%-*}" > $TMPFILE
-		if [ "$?" ] ; then sh < $TMPFILE ; fi
+		if [ "$?" ] ; then 
+			sh < $TMPFILE  
+		else
+			echo "failed."
+		fi
 	else
 		echo -n "Initializing plugins.."
 		munin-node-configure --shell > $TMPFILE
-		if [ "$?" ] ; then sh < $TMPFILE ; fi
+		if [ "$?" ] ; then
+			sh < $TMPFILE
+		else 
+			echo "failed."
+		fi
 	fi
 	echo "done."
 	rm $TMFILE
