version 1.3.3 for debian/experimental
git-svn-id: svn://munin-monitoring.org/munin/branches/debian@1364 47311dc8-50f3-0310-b975-824c5c5ab7df

diff --git a/experimental/node/node.d.linux/df.in b/experimental/node/node.d.linux/df.in
--- a/experimental/node/node.d.linux/df.in
+++ b/experimental/node/node.d.linux/df.in
@@ -1,11 +1,18 @@
-#!/bin/sh
+#!@@PERL@@
+# -*- perl -*-
 #
-# Script to monitor disk usage.
+# Plugin to monitor disk usage. Rewrite based on original shell-based version
 #
 # Parameters understood:
 #
-# 	config   (required)
-# 	autoconf (optional - used by munin-config)
+#       config   (required)
+#       autoconf (optional - used by munin-config)
+#
+# Environment
+#       exclude: space separated list if fs types to exclude.
+#                iso9660 by default
+#
+# $Id$
 #
 # Magic markers (optional - used by munin-config and installation
 # scripts):
@@ -13,50 +20,87 @@
 #%# family=auto
 #%# capabilities=autoconf
 
-MAXLABEL=20
+use strict;
+use Munin::Plugin;
 
-if [ "$1" = "autoconf" ]; then
-	echo yes
-	exit 0
-fi
+my %mounts;
 
-clean_name() {
-    echo $1 $7 $2 | sed 's/[\/.-]/_/g'| awk "{ 
-	if (\$3 == \"tmpfs\")
-		n=\$1\$2
-	else
-		n=\$1
-	print n
-	}"
+open (MOUNTS,"/proc/mounts") or die "Could not /proc/mounts for reading.";
+while (<MOUNTS>) {
+    # Does perl really not have any shorthand for this? I guess it has.
+    if ( /^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/ ) {
+	$mounts{$2}=$3;
+    }
+}
+close MOUNTS;
+
+my $exclude=$ENV{'exclude'} || 'iso9660';
+my $dfopts = "-P -l ".join(' -x ',('',split('\s+',$exclude)));
+
+sub print_values() {
+
+    # Read from df
+    open (DF,"df $dfopts |") or die "Could not open pipe from df, $!";
+    <DF>; # Skip the header
+    while (<DF>) {
+	next if /\/\//;
+	
+	# Parse the output
+	if ( /^(\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\S+)\s+(\S+)/ ) {
+	    my $fs=$mounts{$6};
+	    my $ps=$5;
+	    my $name=clean_fieldname($1);
+
+	    $ps =~ s/\%//;
+	    print $name, ".value ", $ps, "\n";
+	}
+    }
+    close DF;
+    die "Error executing df. Exit code $?\n" if $?;
 }
 
+if ( $ARGV[0] eq "autoconf" ) {
+    if (`@@PERL@@ $0` eq "" ) {
+	print "no\n";
+	exit 1;
+    } else {
+	print "yes\n";
+	exit 0;
+    }
+}
 
-if [ "$1" = "config" ]; then
+if ( $ARGV[0] eq "config" ) {
 
-	echo 'graph_title Filesystem usage (in %)'
-	echo 'graph_args --upper-limit 100 -l 0'
-	echo 'graph_vlabel %'
-	echo 'graph_category disk'
-	echo 'graph_info This graph shows disk usage on the machine.'
-	df -T -P -l -x none -x unknown -x udf -x iso9660 -x romfs -x ramfs | sed 1d | grep -v "//" | sort | while read i; do
-		name=`clean_name $i`
-		echo -n "$name.label "
-		echo $i | awk "{ 
-			dir=\$7
-			if (length(dir) <= $MAXLABEL)
-				print dir
-			else
-				printf (\"...%s\n\", substr (dir, length(dir)-$MAXLABEL+4, $MAXLABEL-3)) 
-			print \"$name.info \" \$7 \" (\" \$2 \") -> \" \$1;
-		}"
-		echo "$name.warning 92"
-		echo "$name.critical 98"
-	done
-	exit 0
-fi
+    # The headers
+    print "graph_title Disk usage (in %)\n";
+    print "graph_args --upper-limit 100 -l 0\n";
+    print "graph_vlabel %\n";
+    print "graph_scale no\n";
+    print "graph_category disk\n";
 
-df -T -P -l -x none -x unknown -x udf -x iso9660 -x romfs -x ramfs | sed 1d | grep -v "//" | while read i; do
-	name=`clean_name $i`
-	echo -n "$name.value "
-	echo $i | awk '{ print $6 }' | cut -f1 -d%
-done
+    # Read from df
+    open (DF,"df $dfopts |") or die "Unable to open pipe from df: $!";
+    <DF>; # Skip the header
+    while (<DF>) {
+	next if /\/\//;
+	
+	# Parse the output
+	if ( /^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/ ) {
+	    my $fs=$mounts{$6};
+	    my $dir=$6;
+	    my $name=clean_fieldname($1);
+
+	    # Create and print labels
+	    print $name, ".label ", $dir, "\n";
+
+	    # FIXME: These ought to be tunable
+	    print "$name.warning 92\n";
+	    print "$name.critical 98\n";
+	}
+    }
+    close DF;
+    die "Error executing df. Exit code $?\n" if $?;
+    exit 0;
+}
+
+print_values();
