Apply patch by Tom Feiner to not make the automatic plugin detection fail if one plugin has an error. (Closes: #539886)
git-svn-id: svn://munin-monitoring.org/munin/branches/debian@2604 47311dc8-50f3-0310-b975-824c5c5ab7df

diff --git a/squeeze/trunk/debian/munin-node.postinst b/squeeze/trunk/debian/munin-node.postinst
--- a/squeeze/trunk/debian/munin-node.postinst
+++ b/squeeze/trunk/debian/munin-node.postinst
@@ -28,25 +28,35 @@ fixperms() {
 
 init_plugins() {
 	TMPFILE=`mktemp /tmp/munin-node.configure.XXXXXXXXXX`
+	TMPFILE_STDERR=`mktemp /tmp/munin-node.configure.err.XXXXXXXXXX`
+	MUNIN_NODE_CONF_LOG="/var/log/munin/munin-node-configure.log"
 	if [ "$prevver" ]; then
+		MUNIN_NODE_CMD="munin-node-configure --shell --newer "${prevver%-*}""    
 		echo -n "Initializing new plugins.."
-		munin-node-configure --shell --newer "${prevver%-*}" > $TMPFILE || rm -f $TMPFILE
-		if [ -f $TMPFILE ] ; then 
-			sh < $TMPFILE  
-		else
-			echo "failed."
-		fi
 	else
+		MUNIN_NODE_CMD="munin-node-configure --shell"
 		echo -n "Initializing plugins.."
-		munin-node-configure --shell > $TMPFILE || rm -f $TMPFILE
-		if [ -f $TMPFILE ] ; then
-			sh < $TMPFILE
-		else 
-			echo "failed."
-		fi
+    fi
+
+	# munin-node-conf returns 1 if case of partial plugin autoconf
+	# errors. We need to ignore these errors as even one plugin
+	# can fail the entire process. See Debian bug #539886 for details.
+	$MUNIN_NODE_CMD 2>$TMPFILE_STDERR >$TMPFILE || true
+	if [ -f $TMPFILE ]; then
+		DATE=`date '+%b %d %T'`
+		echo "$DATE - Starting $MUNIN_NODE_CMD" >> $MUNIN_NODE_CONF_LOG
+		cat $TMPFILE >> $MUNIN_NODE_CONF_LOG
+        if [ -s $TMPFILE_STDERR ]; then
+			echo "The following errors were reported by $MUNIN_NODE_CMD" \
+			>> $MUNIN_NODE_CONF_LOG 
+			cat $TMPFILE_STDERR >> $MUNIN_NODE_CONF_LOG
+        fi
+		sh < $TMPFILE
+	else 
+		echo "failed."
 	fi
 	echo "done."
-	rm -f $TMPFILE
+	rm -f $TMPFILE $TMPFILE_STDERR
 	echo -n "Restarting munin-node.."
 	invoke-rc.d munin-node restart
 }
